//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS_ASP_NET.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class IncidentReport
    {
        public int IncidentReportID { get; set; }
        public int SiteID { get; set; }
        public int UserID { get; set; }
        public string IncidentLocation { get; set; }
        public string IncidentDescription { get; set; }
        public string SecurityOfficerName { get; set; }
        public string Shift { get; set; }
        public string PrimaryInvolvedPerson { get; set; }
        public string DriverLicenseNo { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public System.DateTime BirthDate { get; set; }
        //public Nullable<DateTime> BirthDate { get; set; }
        public string SupervisorName { get; set; }
        public string VehicleMake { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleLicensePlateNo { get; set; }
        public Nullable<int> VehicleStateID { get; set; }
        public Nullable<int> TrailerAttachmentID { get; set; }
        public string TrailerLicensePlateNo { get; set; }
        public string TrailerVIN { get; set; }
        public Nullable<int> TrailerStateID { get; set; }
        public Nullable<byte> CurrentlyInsured { get; set; }
        public string PolicyNumber { get; set; }
        public string WorkSite { get; set; }
        public string Vendor { get; set; }
        public string SiteType { get; set; }
        public string Status { get; set; }
        public string Disposition { get; set; }
        public bool Signature { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string Notes { get; set; }
        public string SupervisorPhoneNumber { get; set; }
        public System.DateTime IncidentDateTime { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
