//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS_ASP_NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trailer
    {
        public int TrailerID { get; set; }
        public int TrailerAttachmentID { get; set; }
        public int TrailerStateID { get; set; }
        public int TrailerTypeID { get; set; }
        public string TrailerPlateNo { get; set; }
        public string TrailerVIN { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual StateProvince StateProvince { get; set; }
        public virtual TrailerAttachment TrailerAttachment { get; set; }
    }
}
