//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS_ASP_NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VisitMain()
        {
            this.VisitDetails = new HashSet<VisitDetail>();
        }
    
        public int VisitMainID { get; set; }
        public int VisitorTypeID { get; set; }
        public int SiteID { get; set; }
        public System.DateTime CheckInMainTime { get; set; }
        public string CheckInDevice { get; set; }
        public int CheckInMainUserID { get; set; }
        public int CheckInMainGateID { get; set; }
        public Nullable<int> CheckInMainTrailerID { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
        public string CheckOutDevice { get; set; }
        public Nullable<int> CheckOutMainGateID { get; set; }
        public Nullable<int> CheckOutMainUserID { get; set; }
        public Nullable<int> CheckOutMainTrailerID { get; set; }
        public string PlacardNo { get; set; }
        public Nullable<byte> VehicleSearchConsent { get; set; }
        public Nullable<int> UnitNo { get; set; }
        public Nullable<int> SectionSector { get; set; }
        public string EmergencyVehicleType { get; set; }
        public string Location { get; set; }
        public string Organization { get; set; }
        public string PassNumber { get; set; }
        public string ConeNumber { get; set; }
        public Nullable<int> ConeColorID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public string VehicleSearchResult { get; set; }
    
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitDetail> VisitDetails { get; set; }
        public virtual VisitorType VisitorType { get; set; }
    }
}
